z3us-dapps/z3us

apps/extension/chrome.ts
apps/extension/firefox.ts
apps/extension/src/hooks/use-vault.tsx
apps/extension/src/hooks/use-watch-transactions.tsx
apps/extension/src/popup/app_.tsx
apps/extension/src/services/react-query/queries/radix.ts

Show new tx notification when popup is open

Tx notification

---

packages/config/package.json
packages/ui/src/components/accordion/index.tsx
packages/ui/src/components/alert-card/index.tsx
packages/ui/src/components/button-group/index.tsx
packages/ui/src/components/button-tip-feedback/index.tsx
packages/ui/src/components/button/index.tsx
packages/ui/src/components/input/index.tsx
packages/ui/src/components/input/input-feedback.tsx
packages/ui/src/components/loader-bars/index.tsx
packages/ui/src/components/pill/index.tsx
packages/ui/src/components/price-label/index.tsx
packages/ui/src/components/price-ticker/ticker.tsx
packages/ui/src/components/toasts/index.tsx
yarn.lock

- upgrade `eslint-config-next`
- fixed errors related to `eslint-config-next` upgrade

chore: fixed errors related to eslint-config-next upgrade

---

apps/extension/src/containers/hardware-wallet/steps/1-import-accounts/index.tsx

Quick hotfixes for hw

---

apps/website/docs/api-v1.mdx
apps/website/docs/introduction.mdx

Docs(website) - fix spelling

---

apps/extension/src/config.tsx

added new color presets for account cards

feat(Extension): added new color presets for account cards

---

README.md

add docs for Firefox extension local installation

docs(extension): add docs for Firefox extension local installation

---

apps/extension/src/containers/wallet-panel/staking/index.tsx

fix: spelling mistake

---

apps/extension/src/components/z3us-menu/index.tsx
apps/extension/src/containers/wallet-panel/accounts/account-switcher/account-info/index.tsx

- fixes issue where the wallet name shows correctly in the text box instead of the id
- style fixes

refactor: improve ui for the multi wallet menu

---

apps/extension/package.json
apps/extension/src/components/address-book-selector/index.tsx
apps/extension/src/containers/wallet-panel/accounts/account-switcher/index.tsx

v1.0.9+ext

---

apps/extension/src/containers/wallet-panel/staking/stake-modal/index.tsx

validator list was hard crashing, adding this check resolves this issue.

fix: hard crash when validator not present

---

apps/extension/src/components/account-selector/index.tsx

Fix address name on account selector

fix: account selector name

---

apps/extension/src/components/account-selector/index.tsx
apps/extension/src/components/locked-panel/index.tsx

Correctly set initial account state

Fix unlock

---

apps/extension/e2e/bootstrap.js
apps/extension/e2e/e2e-website-extension.spec.js
apps/extension/jest.config.js
apps/extension/package.json
apps/extension/src/containers/onboarding/steps/1-start/check-item/index.tsx
apps/extension/src/containers/onboarding/steps/1-start/index.tsx
apps/extension/src/containers/onboarding/steps/2a-generate-phrase/index.tsx
apps/extension/src/containers/onboarding/steps/4-create-password/index.tsx
apps/extension/src/containers/onboarding/steps/5-create-wallet/index.tsx
apps/extension/src/containers/wallet-panel/accounts/account-switcher/index.tsx
apps/website/components/header/index.tsx
packages/ui/src/components/input/index.tsx
yarn.lock

first e2e test us puppeteer,
simple test to test extension loads on website and the `Pill` components are present and the type is correct.

Test: e2e test for wallet creation

---

apps/extension/src/components/account-selector/index.tsx
apps/extension/src/containers/wallet-panel/settings/index.tsx
apps/extension/src/containers/wallet-panel/settings/token-management-settins/token-burn-modal/index.tsx
apps/extension/src/containers/wallet-panel/settings/token-management-settins/token-create-modal/index.tsx
apps/extension/src/containers/wallet-panel/settings/token-management-settins/token-mint-modal/index.tsx
packages/ui/src/components/input/index.tsx

Allows users to create/minb/burn tokens

Token management

---

apps/extension/src/containers/hardware-wallet/steps/1-import-accounts/index.tsx

ensure that the hardware wallet account show on import

style: fix the onboarding account styles for hardware wallet

---

apps/extension/src/containers/notification/sign/index.tsx
apps/extension/src/hooks/use-message.tsx
apps/extension/src/hooks/use-signature.tsx
apps/extension/src/hooks/use-transaction.tsx
apps/extension/src/store/index.ts
apps/extension/src/store/toasts.ts
apps/extension/src/store/types.ts
apps/website/components/header/index.tsx
apps/website/components/mdx-theme/index.tsx
apps/website/components/pages/airdrop/index.tsx
apps/website/docs/airdrop.mdx
apps/website/hooks/use-z3us-wallet/index.tsx
apps/website/pages/airdrop.tsx
apps/website/pages/meta.json
apps/website/pages/terms.tsx

feat: airdrop subscribe page

---

apps/extension/src/containers/wallet-panel/accounts/token-row/index.tsx
apps/extension/src/containers/wallet-panel/accounts/token-row/token-price/index.tsx

fix for token list large numbers not truncating properly

style: fix truncate issue with large numbers

---

apps/extension/src/components/token-list-settings-modal/index.tsx
apps/extension/src/containers/toasts/index.tsx
apps/extension/src/store/types.ts
packages/ui/src/components/toasts/toast/index.tsx
packages/ui/src/theme/dark-colors.ts
packages/ui/src/theme/light-colors.ts

improved styles for the toast colours and fix issue so they stack.

style: improved styles for the toast colours and fix issue so they stack

---

apps/extension/src/services/dogecubex.ts

The new APIs return exactly the same data, just under different urls.

DogeCubeX - use new API urls.

---

apps/extension/src/components/activity-item/activity-links/index.tsx

feat: added transaction date to transaction popup

---

apps/extension/src/components/token-selector/index.tsx
apps/extension/src/components/token-selector/token-item/index.tsx

new token selector dialog component.

feat: added new token selector dialog component

---

apps/extension/src/components/account-selector/index.tsx
apps/extension/src/components/address-book-selector/index.tsx
apps/extension/src/containers/wallet-panel/accounts/send-token/index.tsx
apps/extension/src/containers/wallet-panel/swap/pool-selector/index.tsx

for better UX.
account selector
address book selector

feat: updated dropdowns to select components

---

apps/extension/src/components/z3us-menu/index.tsx
apps/extension/src/containers/onboarding/steps/2a-generate-phrase/index.tsx

Revert "fix: add restore button to menu"

---

apps/extension/src/containers/wallet-panel/staking/stake-modal/index.tsx

Added useEffect in modal to ensure that the validator address is not
stale when the validator list is filtered.

fix: critical issue with stake address

---

apps/extension/src/components/info-stat-block/index.tsx
apps/extension/src/containers/wallet-panel/swap/fee-box/index.tsx
apps/extension/src/containers/wallet-panel/swap/index.tsx
apps/extension/src/containers/wallet-panel/swap/swap-modal/index.tsx
packages/ui/src/components/alert-dialog/index.tsx
packages/ui/src/components/dialog/index.tsx

fix - various style fixes

---

apps/extension/src/components/account-address/index.tsx
apps/extension/src/containers/wallet-panel/accounts/account-switcher/account-info/index.tsx
packages/ui/src/components/tool-tip/index.tsx

- added copy icon
- removed icon to edit background for card (accessible via settings)
- added tooltip to show full address

[Refactor] - account card updates 

---

apps/extension/src/components/account-address/index.tsx
apps/extension/src/components/locked-panel/index.tsx
apps/extension/src/components/slippage-box/index.tsx
apps/extension/src/components/z3us-menu/index.tsx
apps/extension/src/containers/notification/connect/index.tsx
apps/extension/src/containers/notification/transaction/components/actions-preview.tsx
apps/extension/src/containers/notification/transaction/index.tsx
apps/extension/src/containers/wallet-panel/settings/index.tsx
apps/extension/src/containers/wallet-panel/settings/key-management-settings/export-private-key/index.tsx
apps/extension/src/popup/app_.tsx
apps/extension/src/utils/sleep.ts

Fix/zgod various UI fixes

---

apps/extension/src/components/unlocked-panel/index.tsx
apps/extension/src/containers/notification/encrypt/index.tsx
apps/extension/src/containers/notification/index.tsx
apps/extension/src/containers/notification/sign/index.tsx

Display message to encrypt/sign

---

apps/extension/src/components/activity-item/activity-links/index.tsx
apps/extension/src/components/activity-item/index.tsx
apps/extension/src/hooks/react-query/queries/market.ts
apps/extension/src/hooks/use-transaction-change.tsx
apps/extension/src/services/swap.ts

Add tx value details to popup

---

README.md

docs: added beta readme

---

apps/extension/src/components/no-results-placeholder/index.tsx
apps/extension/src/containers/wallet-panel/accounts/account-activity/index.tsx
apps/extension/src/containers/wallet-panel/accounts/token/index.tsx

fix for load more on activity and token lists.
also fix for activity lists with no activity always showing a loading component.

fix: fix for load more on activity and token lists

---

apps/extension/package.json
apps/extension/src/components/activity-item/activity-links/index.tsx
apps/extension/src/components/token-list-settings-modal/token/index.tsx
apps/extension/src/config.tsx
apps/extension/src/containers/notification/transaction/index.tsx
apps/extension/src/containers/wallet-panel/accounts/send-token/send-token-review/index.tsx
apps/extension/src/containers/wallet-panel/accounts/token-info/index.tsx
apps/extension/src/containers/wallet-panel/settings/accounts/index.tsx
apps/extension/src/containers/wallet-panel/settings/address-book/index.tsx
apps/extension/src/containers/wallet-panel/staking/index.tsx
apps/extension/src/containers/wallet-panel/staking/stake-item/index.tsx
apps/extension/src/containers/wallet-panel/staking/validator-item/index.tsx
apps/extension/src/containers/wallet-panel/swap/swap-modal/index.tsx
apps/extension/src/hooks/use-explorer-url.tsx
apps/extension/src/lib/background/notifications.ts

v1.0.42+ext

---

apps/extension/content_matches.json

needed for integration of Hermes Protocol

Adding RadixCharts

---

packages/ui/src/components/button/index.tsx
packages/ui/src/components/button/styles.css.ts
packages/ui/src/components/card-buttons/index.tsx
packages/ui/src/components/copy-address-button/index.tsx
packages/ui/src/components/image-icon/image-icon.css.ts
packages/ui/src/components/image-icon/index.tsx
packages/ui/src/components/nft-image-icon/index.tsx
packages/ui/src/components/resource-image-icon/index.tsx
packages/ui/src/pages/accounts/components/overlay-asset-icons/index.tsx
packages/ui/src/pages/accounts/components/table/asset-name-cell/index.tsx
packages/ui/src/pages/accounts/components/table/pool-cell/index.tsx
packages/ui/src/pages/accounts/components/table/validator-cell/index.tsx

refactor for removing `isMobile` for buttons

refactor: remove isMobile for button

---

packages/ui/src/components/card-buttons/index.tsx
packages/ui/src/pages/transfer/home/components/transfer-form-fields/index.tsx

feat: transfer update account when account search params are present

---

packages/ui/src/components/layout/transaction/index.tsx
packages/ui/src/components/layout/transaction/styles.css.ts

style: added styles for transaction message

---

apps/extension/src/hooks/modal/use-password-modal.tsx
apps/extension/src/pages/app/components/settings.tsx
packages/ui/src/components/select/index.tsx

fix: fix select for max styles

---

apps/extension/src/hooks/modal/use-password-modal.tsx
apps/extension/src/pages/app/components/settings.tsx
packages/ui/src/components/select/index.tsx

Revert "fix: fix select for max styles"

---

.vscode/settings.json
packages/ui/src/components/table/index.tsx
packages/ui/src/pages/accounts/components/table/asset-change-cell/index.tsx
packages/ui/src/pages/accounts/components/table/validator-change-cell/index.tsx
packages/ui/src/pages/accounts/components/table/validator-fee-cell/index.tsx
packages/ui/src/pages/accounts/lpus/index.tsx
packages/ui/src/pages/accounts/lsus/index.tsx

fix: LSU table issue

---

apps/extension/public/images/token-images/nft-placeholder.svg
packages/ui/src/components/layout/transaction/index.tsx
packages/ui/src/components/resource-image-icon/index.tsx
packages/ui/src/components/resource/resource.tsx
packages/ui/src/components/snippet/resource.tsx
packages/ui/src/context/images-provider.tsx
packages/ui/src/hooks/dapp/use-total-balance.ts
packages/ui/src/pages/accounts/components/assets-list/index.tsx
packages/ui/src/pages/accounts/components/table/asset-change-cell/index.tsx
packages/ui/src/pages/accounts/components/table/asset-name-cell/index.tsx
packages/ui/src/pages/accounts/components/table/pool-cell/index.tsx
packages/ui/src/pages/accounts/components/table/validator-cell/index.tsx
packages/ui/src/pages/accounts/components/table/validator-change-cell/index.tsx

chore: added nft image

---

apps/extension/src/pages/app/components/settings.tsx
packages/ui/src/components/navigation/header-navigation/index.tsx
packages/ui/src/components/select/index.tsx

feat: added prop to have custom dropdown width for <SimpleSelect />

---

apps/extension/src/components/forms/add-persona-form.tsx
apps/extension/src/components/modals/select-persona-modal.tsx

- add tooltip
- changed instruction language on modal

fix: improve add persona modal UX

---

packages/ui/src/pages/accounts/components/activity-list/components/activity-list/index.tsx

currently no loading state and the activity just flashes in.

refactor: show loading state for activity

---

packages/ui/src/hooks/dapp/use-balances.ts
packages/ui/src/pages/accounts/components/activity-list/components/balance-pie-chart/index.tsx
packages/ui/src/types/index.ts

Display pool names on pie chart

---

apps/extension/src/pages/interaction/home/components/transaction/constants.ts
apps/extension/src/pages/interaction/home/components/transaction/consts.ts
apps/extension/src/pages/interaction/home/components/transaction/preview.tsx
apps/extension/src/pages/interaction/home/components/transaction/styles.css.ts
apps/extension/src/types/transaction.ts
packages/ui/src/pages/settings/wallet/index.tsx

Group tx preview items for readability

---

apps/extension/src/components/forms/customize-guarantee-form.tsx
apps/extension/src/components/modals/customize-guarantee-modal.tsx
apps/extension/src/hooks/modal/use-customize-fee-modal.tsx
apps/extension/src/hooks/modal/use-customize-guarantee-modal.tsx
apps/extension/src/hooks/transaction/use-intent.tsx
apps/extension/src/pages/app/main.tsx
apps/extension/src/pages/interaction/home/components/interaction/transaction.tsx
apps/extension/src/pages/interaction/home/components/transaction/customize-guarantee-trigger.tsx
apps/extension/src/pages/interaction/home/components/transaction/manifest.tsx
apps/extension/src/pages/interaction/home/components/transaction/preview.tsx
apps/extension/src/radix/manifest.ts
apps/extension/src/radix/transaction.ts
apps/extension/src/types/transaction.ts
apps/website/src/components/layouts/app-page/index.tsx
packages/ui/src/components/layout/index.tsx
packages/ui/src/hooks/dapp/use-balances.ts

Add customize guarantees modal for predicted depisits

---

packages/ui/package.json
packages/ui/src/components/radio-group/index.tsx
packages/ui/src/components/radio-group/styles.css.ts
packages/ui/src/hooks/dapp/use-entity-details.ts
packages/ui/src/pages/settings/accounts/index.tsx
yarn.lock

Add third party deposit settings
